### ISSUE TITLE
Update installation command to support for python3 version 

### ISSUE THREAD

**Issue by kumar550** [deep-compute/kwikapi.tornado#13]
**Readme:**
![screen shot 2018-06-06 at 11 44 45 am](https://user-images.githubusercontent.com/18277890/41020498-bca70216-6980-11e8-8f67-e7f6efbb51e3.png)

@RamanjaneyuluIdavalapati 
- Can you please update the installation command to support for python3
- It's little clumsy to see multiple repo's like (kwikapi, kwikapi.tornado) which one to choose 

Thank you

**Comment by jaswanth098** [comment]
This is changed in README closing this
